import { formatArea } from './gis';
import type { Review } from './types';

const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reviewReport(review:Review):string {
  const p=review.recordSnapshot.properties, analysis=review.analysis;
  const table=(entries:typeof analysis.zones)=>entries.length?`<table><thead><tr><th>Overlay</th><th>Category</th><th>Area</th><th>Parcel share</th><th>Source</th></tr></thead><tbody>${entries.map(z=>`<tr><td>${escape(z.name)}</td><td>${escape(z.category)}</td><td>${escape(formatArea(z.area))}</td><td>${z.percent.toFixed(2)}%</td><td>${escape(z.source)}</td></tr>`).join('')}</tbody></table>`:'<p>No mapped overlap in the available records. Coverage may be incomplete.</p>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escape(p.name)} — Aklan Planner review</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{font:16px/1.6 system-ui,sans-serif;color:#19303a;max-width:1000px;margin:40px auto;padding:0 24px}h1{font-size:32px}h2{font-size:20px;margin-top:30px}.label{color:#466773}.notice{background:#fff5d9;border-left:4px solid #d1a634;padding:14px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;border-bottom:1px solid #ccd8db;text-align:left;vertical-align:top}.notes{white-space:pre-wrap}button{padding:10px 16px}@media print{button{display:none}body{margin:0;max-width:none}tr{break-inside:avoid}}</style></head><body><button onclick="window.print()">Print / save PDF</button><p class="label">AKLAN PLANNER · ${p.demo?'DEMONSTRATION':'WORKSPACE REVIEW'}</p><h1>${escape(p.name)}</h1><div class="notice">${p.demo?'Synthetic demonstration record. Does not describe a real property.':'User-maintained GIS record. Draft zones and parcel sketches are not approved zoning or certified cadastral boundaries.'} This review is not a permit, zoning clearance, or hazard certification.</div><p><strong>Location:</strong> ${escape([p.barangay,p.municipality,'Aklan'].filter(Boolean).join(', '))}<br><strong>Reference:</strong> ${escape(p.reference||'Not recorded')}<br><strong>Parcel source:</strong> ${escape(p.source)}<br><strong>Source date:</strong> ${escape(p.sourceDate||'Unknown')}<br><strong>Geometry status:</strong> ${escape(p.verification)}<br><strong>Calculated area:</strong> ${escape(formatArea(analysis.area))}</p><h2>Review finding</h2><p>${escape(analysis.finding)}</p><p><strong>Reviewer:</strong> ${escape(review.author)} · ${escape(review.status)}<br><strong>Saved:</strong> ${escape(review.createdAt)}<br><strong>Review ID:</strong> ${escape(review.id)}</p><div class="notes">${escape(review.note)}</div><h2>Zone overlaps</h2>${table(analysis.zones)}<p>Coverage in available zone polygons: ${analysis.zoneCoverage.toFixed(2)}%. Overlapping zones: ${analysis.conflictingZones?'Yes — requires correction or review':'No overlapping area detected'}.</p><h2>Hazard overlaps</h2>${table(analysis.hazards)}<h2>Limits and method</h2><ul>${analysis.warnings.map(w=>`<li>${escape(w)}</li>`).join('')}</ul><p>Area method: Turf spherical area on WGS84 coordinates. Zone coverage uses the union of intersecting polygons to avoid counting the same area twice. Percentages describe mapped area; they are not probabilities or model confidence. The saved review retains the parcel and overlay snapshots used for the analysis.</p><p class="label">Dataset snapshot: ${review.datasetSnapshot.length} relevant overlays. Exported ${escape(new Date().toISOString())}. Administrative display boundaries: geoBoundaries, NAMRIA / PSA / OCHA Philippines, 2020 reference. Esri imagery is used in the workbench; this text report does not reproduce imagery.</p></body></html>`;
}
